name: streamlit
channels:
  - conda-forge
  - defaults
dependencies:
  - aiohttp=3.9.0
  - aiosignal=1.3.1
  - altair=5.1.2
  - appnope=0.1.3
  - asttokens=2.4.1
  - attrs=23.1.0
  - aws-c-auth=0.7.6
  - aws-c-cal=0.6.9
  - aws-c-common=0.9.8
  - aws-c-compression=0.2.17
  - aws-c-event-stream=0.3.2
  - aws-c-http=0.7.14
  - aws-c-io=0.13.35
  - aws-c-mqtt=0.9.9
  - aws-c-s3=0.3.23
  - aws-c-sdkutils=0.1.12
  - aws-checksums=0.1.17
  - aws-crt-cpp=0.24.6
  - aws-sdk-cpp=1.11.182
  - backports=1.0
  - backports.functools_lru_cache=1.6.5
  - blinker=1.7.0
  - blosc=1.21.5
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.21.0
  - ca-certificates=2023.11.17
  - cachetools=5.3.2
  - cairo=1.18.0
  - cffi=1.16.0
  - cfitsio=4.3.0
  - charset-normalizer=3.3.2
  - click=8.1.7
  - click-plugins=1.1.1
  - cligj=0.7.2
  - colorama=0.4.6
  - comm=0.1.4
  - contourpy=1.2.0
  - cryptography=41.0.5
  - cycler=0.12.1
  - db-dtypes=1.1.1
  - debugpy=1.8.0
  - decorator=5.1.1
  - exceptiongroup=1.1.3
  - executing=2.0.1
  - expat=2.5.0
  - fastavro=1.9.0
  - fiona=1.9.5
  - folium=0.15.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.12.1
  - freexl=2.0.0
  - frozenlist=1.4.0
  - gdal=3.8.0
  - geopandas=0.14.1
  - geopandas-base=0.14.1
  - geos=3.12.0
  - geotiff=1.7.1
  - gettext=0.21.1
  - gflags=2.2.2
  - giflib=5.2.1
  - gitdb=4.0.11
  - gitpython=3.1.40
  - glog=0.6.0
  - google-api-core=2.14.0
  - google-api-core-grpc=2.14.0
  - google-auth=2.23.4
  - google-auth-oauthlib=1.1.0
  - google-cloud-bigquery=3.13.0
  - google-cloud-bigquery-core=3.13.0
  - google-cloud-bigquery-storage=2.22.0
  - google-cloud-bigquery-storage-core=2.22.0
  - google-cloud-core=2.3.3
  - google-crc32c=1.1.2
  - google-resumable-media=2.6.0
  - googleapis-common-protos=1.61.0
  - grpcio=1.59.3
  - grpcio-status=1.59.3
  - hdf4=4.2.15
  - hdf5=1.14.2
  - icu=73.2
  - idna=3.4
  - importlib-metadata=6.8.0
  - importlib_metadata=6.8.0
  - importlib_resources=6.1.1
  - ipykernel=6.26.0
  - ipython=8.17.2
  - ipywidgets=8.1.1
  - jedi=0.19.1
  - jinja2=3.1.2
  - joblib=1.3.2
  - json-c=0.17
  - jsonschema=4.19.2
  - jsonschema-specifications=2023.7.1
  - jupyter_client=8.6.0
  - jupyter_core=5.5.0
  - jupyterlab_widgets=3.0.9
  - kealib=1.5.2
  - kiwisolver=1.4.5
  - krb5=1.21.2
  - lcms2=2.15
  - lerc=4.0.0
  - libabseil=20230802.1
  - libaec=1.1.2
  - libarchive=3.7.2
  - libarrow=14.0.1
  - libarrow-acero=14.0.1
  - libarrow-dataset=14.0.1
  - libarrow-flight=14.0.1
  - libarrow-flight-sql=14.0.1
  - libarrow-gandiva=14.0.1
  - libarrow-substrait=14.0.1
  - libblas=3.9.0
  - libboost-headers=1.83.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.4.0
  - libcxx=16.0.6
  - libdeflate=1.19
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgdal=3.8.0
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libglib=2.78.1
  - libgoogle-cloud=2.12.0
  - libgrpc=1.59.3
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - libkml=1.3.0
  - liblapack=3.9.0
  - libllvm15=15.0.7
  - libnetcdf=4.9.2
  - libnghttp2=1.58.0
  - libopenblas=0.3.24
  - libparquet=14.0.1
  - libpng=1.6.39
  - libpq=16.1
  - libprotobuf=4.24.4
  - libre2-11=2023.06.02
  - librttopo=1.1.0
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libspatialite=5.1.0
  - libsqlite=3.44.0
  - libssh2=1.11.0
  - libthrift=0.19.0
  - libtiff=4.6.0
  - libutf8proc=2.8.0
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxml2=2.11.5
  - libzip=1.10.1
  - libzlib=1.2.13
  - llvm-openmp=17.0.4
  - lz4-c=1.9.4
  - lzo=2.10
  - mapclassify=2.6.1
  - markdown-it-py=3.0.0
  - markupsafe=2.1.3
  - matplotlib-base=3.8.2
  - matplotlib-inline=0.1.6
  - minizip=4.0.3
  - multidict=6.0.4
  - munch=4.0.0
  - munkres=1.1.4
  - ncurses=6.4
  - nest-asyncio=1.5.8
  - networkx=3.2.1
  - nspr=4.35
  - nss=3.94
  - oauthlib=3.2.2
  - openjpeg=2.5.0
  - openssl=3.2.0
  - orc=1.9.0
  - packaging=23.2
  - pandas=2.1.3
  - pandas-gbq=0.19.2
  - parso=0.8.3
  - pcre2=10.42
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=10.1.0
  - pip=23.3.1
  - pixman=0.42.2
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.0.0
  - poppler=23.11.0
  - poppler-data=0.4.12
  - postgresql=16.1
  - proj=9.3.0
  - prompt-toolkit=3.0.40
  - prompt_toolkit=3.0.40
  - proto-plus=1.22.3
  - psutil=5.9.5
  - psycopg2=2.9.7
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyasn1=0.5.0
  - pyasn1-modules=0.3.0
  - pycparser=2.21
  - pydata-google-auth=1.8.2
  - pygments=2.16.1
  - pyjwt=2.8.0
  - pyopenssl=23.3.0
  - pyparsing=3.1.1
  - pyproj=3.6.1
  - pysocks=1.7.1
  - python=3.12.0
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - python_abi=3.12
  - pytz=2023.3.post1
  - pyu2f=0.1.5
  - pyyaml=6.0.1
  - pyzmq=25.1.1
  - re2=2023.06.02
  - readline=8.2
  - referencing=0.30.2
  - requests=2.31.0
  - requests-oauthlib=1.3.1
  - rich=13.6.0
  - rpds-py=0.12.0
  - rsa=4.9
  - rtree=1.1.0
  - scikit-learn=1.3.2
  - scipy=1.11.3
  - setuptools=68.2.2
  - shapely=2.0.2
  - six=1.16.0
  - snappy=1.1.10
  - sqlite=3.41.2
  - stack_data=0.6.2
  - streamlit-folium=0.15.1
  - tenacity=8.2.3
  - threadpoolctl=3.2.0
  - tiledb=2.16.3
  - tk=8.6.13
  - toml=0.10.2
  - toolz=0.12.0
  - tornado=6.3.3
  - tqdm=4.66.1
  - traitlets=5.13.0
  - typing-extensions=4.8.0
  - typing_extensions=4.8.0
  - tzcode=2023c
  - tzdata=2023c
  - tzlocal=5.2
  - uriparser=0.9.7
  - urllib3=2.1.0
  - validators=0.22.0
  - watchdog=3.0.0
  - wcwidth=0.2.10
  - wheel=0.41.3
  - widgetsnbextension=4.0.9
  - xerces-c=3.2.4
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xyzservices=2023.10.1
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.9.2
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - bcrypt==4.0.1
      - beautifulsoup4==4.12.2
      - branca==0.3.1
      - certifi==2023.7.22
      - entrypoints==0.4
      - et-xmlfile==1.1.0
      - extra-streamlit-components==0.1.60
      - faker==20.1.0
      - favicon==0.7.0
      - fonttools==4.45.0
      - htbuilder==0.6.2
      - lxml==4.9.3
      - markdown==3.5.1
      - markdownlit==0.0.7
      - mdurl==0.1.2
      - more-itertools==10.1.0
      - numpy==1.26.2
      - openpyxl==3.1.2
      - patsy==0.5.3
      - plotly==5.18.0
      - plotly-express==0.4.1
      - protobuf==4.25.0
      - pyarrow==14.0.1
      - pydeck==0.8.1b0
      - pymdown-extensions==10.4
      - python-decouple==3.8
      - smmap==5.0.1
      - soupsieve==2.5
      - st-annotated-text==4.0.1
      - st-pages==0.4.5
      - statsmodels==0.14.0
      - streamlit==1.28.2
      - streamlit-aggrid==0.3.4.post3
      - streamlit-authenticator==0.2.3
      - streamlit-camera-input-live==0.2.0
      - streamlit-card==0.0.61
      - streamlit-embedcode==0.1.2
      - streamlit-extras==0.3.5
      - streamlit-faker==0.0.3
      - streamlit-image-coordinates==0.1.6
      - streamlit-keyup==0.2.0
      - streamlit-lottie==0.0.5
      - streamlit-option-menu==0.3.6
      - streamlit-toggle-switch==1.0.2
      - streamlit-vertical-slider==1.0.2
